spring.application.name=shopping

spring.datasource.url=jdbc:mysql://localhost:3306/shopdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dung_1001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

unsplash.access-key=zVSE7yUKHpUt9Kvkx7C0ZtvKAnXTDo3ANMyY9fSEUhE

# Cấu hình Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chongapink@gmail.com
spring.mail.password=zqlalzevjqrpwpcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true